export const LOAD_WEEKS = "LOAD_WEEKS"
export const LOAD_PARTS = "LOAD_PARTS"
export const CHANGE_WEEK = "CHANGE_WEEK"
export const SELECT_PUBLISHER = "SELECT_PUBLISHER"
export const VIEW_PUBLISHER_PARTS = "VIEW_PUBLISHER_PARTS"
export const ADD_PROGRAM = "ADD_PROGRAM"
export const OPEN_PUBLISHER_MODAL = "OPEN_PUBLISHER_MODAL"
export const OPEN_EXPORT_MODAL = "OPEN_EXPORT_MODAL"

