import { Part, PartType, WeekProgram } from "./wol";
import firestore from "firebase/firestore";
import functions from "firebase/functions";
import storage from "firebase/storage";
import auth from 'firebase/auth';
import { Publisher } from "./publisher";
import { ReactNode } from "react";
import { Congregation } from "./congregation";
import { User } from "./user";
import { IDropdownOption } from "@fluentui/react";

export interface InitialState {
  week: WeekProgram;
  weeks: WeekProgram[];
  parts: Part[];
  congregation: Congregation; 
  auth: auth.Auth;
  firestore: firestore.Firestore;
  functions: functions.Functions;
  storage: storage.FirebaseStorage;
  loading: boolean;
  part: Part;
  publisher: Publisher;
  changeWeek: any;
  dismissPanel: any;
  openPanel: any;
  type: PartType;
  isPanelOpen: boolean;
  selectPublisher: any;
  dismissModal: any;
  openModal: any;
  isMobile: boolean;
  isModalOpen: boolean;
  modalChildren: ReactNode;
  viewPublisherParts: any; 
  assignPublisher: any;
  addProgram: any;
  openPublisherModal: any;
  openExportModal: any;
  user: User;
  listener: firestore.Unsubscribe | null;
  openRenameModal: any;
  reloadWeeks: any;
  openSpeakerModal: any;
  openGroupModal: any;
  openEditGroupModal: any;
  talks: IDropdownOption[];
  loadTalks: any;
}
